---
# handlers file for ElasticSearch & Kibana
- name: "ElasticSearch & Kibana reload"
  listen: "ek_restart"
  systemd:
    name: "{{ item }}"
    state: "restarted"
    enabled: True
  loop:
    - "elasticsearch"
    - "kibana"